### ISSUE TITLE
Tests for HTML controllers

### ISSUE THREAD

**Issue by Draiken** [britton-jb/sentinel#20]
Both the Users and the Sessions controllers have been recently introduced, but have been frustratingly buggy to work with. Small errors like mismatched parameters, lost error messages, wrong redirects, etc.

I think specially since this part is supposed to be integrated with an external application and some customizeable parts (eg. views) they need more robust tests.

Providing a default that Just Works is very important

Not sure if you want integration tests or more specialized ones, but either way all the boundaries need to be tested. With that it'll be easier to document how you can extend and customize Sentinel too.

Edit: wording

**Comment by britton-jb** [comment]
I agree. I'm sorry it's not been a great experience for you out of the box. I made a bad call releasing 1.0.0 prematurely, but wanted to get the HTML views out because that was something that a number of people have talked to me about.

My personal use case for Sentinel at this point has been API based, so that has been my primary focus. I'm hoping that this week I'll have some time to really get in and refine the HTML side.

Once again I appreciate the work you've done here.

**Comment by britton-jb** [comment]
Included HTML specs in the v2 branch, which should have a 2.0.0 release in the coming week.
