### ISSUE TITLE
Ability to generate controllers and views during installation

### ISSUE THREAD

**Issue by egeersoz** [britton-jb/sentinel#32]
While I appreciate the "everything but the kitchen sink" approach of this library, I think the inner workings are a bit too opaque.

I think being able to generate one's own controllers and views during installation would go a long way towards customizability.

For example, new user creation via a JSON api seems to be handled through JSON.UserController, but it follows invitation logic where the user provides their email first, confirms it, then creates their password.

What if I want to have the user provide their email AND password during the first step? Currently there isn't a way to do that (unless I missed something - documentation and examples assume too much prior knowledge of Guardian and UeberAuth).

**Comment by britton-jb** [comment]
Yeah, I agree with you that at this point the examples and documentation are definitely more than a bit opaque, as I've spent a bit of time getting familiar with Guardian and Ueberauth.

I think the ability to generate some controllers and views during installation would make sense, but I'm not sure if it's what I'd like to have as the default behavior, in order to allow ease of upgrade of the core module on my part. Definitely something I'd be interesting in adding the behavior for, or making it more explicit in the docs about how to customize individual routes.

It sounds like I might have not made the usage of the confirmable and/or invitable options clear, as the default logic allows for creation of a new user with an email and password in the first step, and if the invitiable flow is enabled, optionally allows users to be created in the multiple step flow, where first the user is created, then they are sent an email to create a password.

**Comment by egeersoz** [comment]
I think some examples of the login flow with popular SPA libraries (such as React and Vue) would help a lot in allowing people to learn how to use Sentinel in conjunction with them.

I know it's a lot to ask, and you probably want to keep Sentinel decoupled from the front-end, but in my experience the more prior knowledge you assume when writing docs, the fewer people tend use the stuff you develop.

Anyway, thank you for taking the time to respond. I'll give Sentinel another shot in the near future. Just looking for a "plug and play" JWT auth library right now and don't have the time to dig too deep.

**Comment by britton-jb** [comment]
Yeah, I'll see if I can throw a SPA example up in the Sentinel Example repo I've got.
It's true, the docs as they are aren't properly geared for no experience needed. I'll work on getting that updated. Thank you very much for the feedback @egeersoz.
